-- Plantilla para resetear passwords en entorno LOCAL.
-- Genera un hash bcrypt y reemplaza HASH_AQUI:
--   node -e "const b=require('bcryptjs'); b.hash('tu_password',10).then(console.log)"
--
-- UPDATE up_users SET password = 'HASH_AQUI' WHERE email IN ('usuario1@example.com', 'usuario2@example.com');
